excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
steps:
- USE="-smartcard" emerge app-emulation/spice
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "X"
  version: ">=0"
