excludes:
{{ template "portage_excludes" }}
#TODO: Why is this service file here?
- ^/usr/lib/systemd/system/pam_namespace.service
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
steps:
- USE="-smartcard" emerge app-emulation/spice
{{ template "portage_build" . }}
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
