excludes:
{{ template "portage_excludes" }}
- ^/usr/local/share/icons/hicolor/icon-theme.cache
- ^/usr/local/share/applications/mimeinfo.cache
- ^/usr/local/share/glib-2.0/schemas/gschemas.compiled
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
# patch for https://bugs.gentoo.org/907049
- cp -rf patches/ /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
