excludes:
{{ template "portage_excludes" }}
- ^/usr/local/share/applications/mimeinfo.cache
- ^/usr/share/applications/mimeinfo.cache
env:
{{ template "portage_env" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
