requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
env:
- LUET_NOLOCK=true
- LUET_YES=true
- HTTP_TIMEOUT=900
prelude:
- curl https://get.mocaccino.org/luet/get_luet_root.sh | sh
- luet install repository/mocaccino-kernel
- luet install kernel/{{.Values.name}} && luet cleanup
- luet install -y kernel/${PACKAGE_NAME/sources/modules}
- |
    kernel=$(ls /usr/src | head -n1) && \ 
    emerge sys-kernel/gentoo-kernel sys-kernel/gentoo-sources && \
    cd /usr/src && rm -rfv linux && ln -s $kernel linux
# Certain modules might require a symlink to the kernel sources inside /lib/module/<module/build
- |
   modules=$(ls /lib/modules | grep mocaccino | head -n1) && \ 
   ln -s /usr/src/linux /lib/modules/$modules/build
