package_dir: "/output"
prelude:
- git clone https://github.com/KDE/mauikit.git
- |
   cd mauikit && git checkout "{{.Values.maui_kit_commit}}" -b build && \
   cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib && make && make install
- |
   git clone https://github.com/Nitrux/maui-shell.git && \
   git checkout "{{.Values.maui_shell_commit}}" -b build && \
   mkdir -p maui-shell/build && cd maui-shell/build && \
   cmake -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BSYMBOLICFUNCTIONS=OFF -DQUICK_COMPILER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu .. && \
   make
steps:
- cd mauikit && make DESTDIR="/output" install
- cd maui-shell/build && make DESTDIR="/output" install
requires:
- category: "buildbase"
  name: "kde-common"
  version: ">=0"
requires_final_images: true
