excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.env /etc/portage/
- emerge -j ${JOBS} --onlydeps --onlydeps-with-rdeps n {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C {{ ( index .Values.labels "emerge.packages" ) }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
