excludes:
{{ template "portage_excludes" }}
prelude:
# LibCPUID
- git clone https://github.com/anrieff/libcpuid --branch v0.4.1
- cd libcpuid
- libtoolize
- autoreconf --install
- ./configure
- make -j`nproc`
# CPU-X
- git clone https://github.com/X0rg/CPU-X.git CPU-X && cd $_
- cmake -B build -DCMAKE_BUILD_TYPE=Release
- cmake --build build
steps:
# Install LibCPUID
- cd libcpuid && make install
# Install CPU-X
- cd CPU-X && cmake --install build
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
