excludes:
{{ template "portage_excludes" }}
- ^/usr/share/applications/mimeinfo.cache
env:
{{ template "portage_env" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "kernel-modules"
  name: "vhba-lts"
  version: ">=0"
