excludes:
{{ template "portage_excludes" }}
# - ^/usr/share/applications/mimeinfo.cache
env:
{{ template "portage_env" . }}
prelude:
- emerge -1 sys-fs/vhba
steps:
{{ template "portage_build" . }}
requires:
- category: "buildbase"
  name: "mocaccino-lts-sources"
  version: ">=0"
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
