excludes:
{{ template "portage_excludes" }}
prelude:
- git clone https://gitlab.gnome.org/World/Fragments.git
- cd Fragments && git checkout 7d94fd0107df498139817842a2b4b22103640c61 && meson --prefix=/usr build && ninja -C build
steps:
- cd Fragments && ninja -C build install
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
