env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go
- GO111MODULE=on
- GITHUB_REPO={{ ( index .Values.labels "github.repo" ) }}
- GITHUB_ORG={{ ( index .Values.labels "github.owner" ) }}
prelude:
- wget https://golang.org/dl/go{{.Values.golang_version}}.linux-{{.Values.arch}}.tar.gz -O golang.tar.gz
- tar -C /usr/local -xzf golang.tar.gz
- go get fyne.io/fyne/v2
- go get fyne.io/fyne/v2/cmd/fyne
- | 
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    git clone https://github.com/$GITHUB_ORG/$GITHUB_REPO.git && git checkout "{{.Values.sha}}" -b build
- |
  export PATH=$PATH:$GOPATH/bin && \
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  cd $GITHUB_REPO/cmd/fyneterm && fyne release -os linux -name "{{.Values.name}}" -appVersion "${PACKAGE_VERSION}" && ls -liah && \
  mkdir out && tar xvf {{.Values.name}}.tar.xz -C out
steps:
- |
  cd $GITHUB_REPO/cmd/fyneterm/out && DESTDIR=/{{.Values.name}} PREFIX=/usr make install
package_dir: "/{{.Values.name}}"
requires:
- category: "layers"
  name: "X"
  version: ">=0"
