category: "apps"
name: "docker-compose"
version: 2.17.2+2
uri:
  - https://github.com/docker/compose
license: "Apache-2.0"
description: "Multi-container orchestration for Docker"
labels:
  emerge.jobs: "1"
  emerge.packages: >-
    app-containers/docker-cli app-containers/docker-compose
provides:
  - name: docker-compose
    category: app-containers
    version: '>=0'
requires:
  - category: "layers"
    name: "system-x"
    version: ">=0"
