excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
steps:
- emerge -1 dev-lang/rust-bin
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C virtual/rust dev-lang/rust-bin
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
