excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "apps"
  name: "grub"
  version: ">=0"
