excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
steps:
{{ template "portage_build" . }}
requires:
- category: "apps"
  name: "grub"
  version: ">=0"
