excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
# - cp -rf package.use /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- cp 99-spice-vdagent /etc/X11/xinit/xinitrc.d/
- chmod +x /etc/X11/xinit/xinitrc.d/99-spice-vdagent
requires:
- category: "layers"
  name: "X"
  version: ">=0"
