excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.* /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable mate-overlay
- emaint sync -r mate-overlay
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "mate"
  version: ">=0"
- category: "layers"
  name: "wayfire"
  version: ">=0"
