excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.* /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable mate-overlay
- emaint sync -r mate-overlay
- USE="x11-backend" emerge -1 gui-libs/wlroots && emerge -1 gui-wm/wayfire gui-apps/wcm
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "mate"
  version: ">=0"
