# Eventhough this currently does not work at all
# I am leaving this here as an example how to use Arch with Luet
image: "archlinux"

prelude:
# Update pacman DB
- pacman -Syy
steps:
# Install packages
- pacman -Sdd --noconfirm extra/firefox nss
excludes:
# Exclude stuff we do not need to ship to user
- ^/var/lib/pacman/.*
- ^/var/cache/pacman/.*
