excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C dev-lang/yasm sys-devel/bin86 sys-power/iasl dev-util/kbuild
requires:
- category: "buildbase"
  name: "qt"
  version: ">=0"
- category: "buildbase"
  name: "virtualbox-modules-lts"
  version: ">=0"
requires_final_images: true
