excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
steps:
{{ template "portage_build" . }}
- emerge -C dev-lang/yasm sys-devel/bin86 sys-power/iasl dev-util/kbuild
requires:
- category: "buildbase"
  name: "qt"
  version: ">=0"
- category: "buildbase"
  name: "virtualbox-modules-lts"
  version: ">=0"
requires_final_images: true
