excludes:
{{ template "portage_excludes" }}
- ^/usr/share/icons/hicolor/icon-theme.cache
- ^/usr/share/applications/avahi-discover.desktop
- ^/usr/share/applications/uxterm.desktop
- ^/var/spool/cups/tmp/
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.license /etc/portage/
- cp -rf package.env /etc/portage/
- emerge -1 -j ${JOBS} app-arch/rpm2targz app-text/docbook-xsl-ns-stylesheets && USE="-cairo -harfbuzz" emerge -1 -j ${JOBS} media-libs/harfbuzz media-libs/freetype && emerge -1 -j ${JOBS} media-libs/mesa
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
# Try build media-plugins/gst-plugins-wavpack first
- emerge -1 -j ${JOBS} media-plugins/gst-plugins-wavpack
- USE="-cairo -harfbuzz" emerge -1 -j ${JOBS} media-libs/harfbuzz media-libs/freetype && emerge -1 -j ${JOBS} media-libs/mesa
{{ template "portage_build_gentoo_binary" . }}
- cp -rv xorg.conf.d/ /etc/X11/
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
- category: "layers"
  name: "sys-fs"
  version: ">=0"
