excludes:
{{ template "portage_excludes" }}
- ^/usr/share/icons/hicolor/icon-theme.cache
- ^/usr/share/applications/avahi-discover.desktop
- ^/usr/share/applications/uxterm.desktop
- ^/var/spool/cups/tmp/
- ^/etc/plymouth/plymouthd.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.* /etc/portage/
- emerge -1 -j ${JOBS} app-arch/rpm2targz app-text/docbook-xsl-ns-stylesheets && USE="-cairo -harfbuzz" emerge -1 -j ${JOBS} media-libs/harfbuzz media-libs/freetype && emerge -1 -j ${JOBS} media-libs/mesa
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
- USE="-cairo -harfbuzz" emerge -1 -j ${JOBS} media-libs/harfbuzz media-libs/freetype && emerge -1 -j ${JOBS} media-libs/mesa
{{ template "portage_build_gentoo_binary" . }}
# cleanup ccache
- CCACHE_DIR=/var/cache/ccache/ ccache -C
- cp -rv xorg.conf.d/ /etc/X11/
# Fix plymouth service file
- sed -i '/^ConditionVirtualization.*/a IgnoreOnIsolate=true' /lib/systemd/system/plymouth-start.service
- sed -i -e 's/KillMode=none/KillMode=mixed/g' /lib/systemd/system/plymouth-start.service
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
- category: "layers"
  name: "sys-fs"
  version: ">=0"
