excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
