excludes:
{{ template "portage_excludes" }}

env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.license /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
