excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
# - cp -rf package.env /etc/portage/
# - cp -rf package.accept_keywords /etc/portage/
# - cp -rf package.mask /etc/portage/
# - cp -rf package.unmask /etc/portage/
# {{ template "portage_prelude_build" . }}
steps:
# {{ template "portage_build" . }}
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge --depclean
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
