excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
- USE="qt5" emerge -1 media-libs/phonon
{{ template "portage_build_gentoo_binary" . }}
requires:
- category: "buildbase"
  name: "kde-common"
  version: ">=0"
requires_final_images: true
