excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.mask /etc/portage/
- USE="-subversion -mercurial" emerge app-portage/layman
- layman -L
# needed for wlogout
- echo "y" | layman -a guru
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- echo "y" | layman -d guru
- emerge -C app-portage/layman dev-python/ssl-fetch
requires:
- category: "layers"
  name: "X"
  version: ">=0"
