image: "alpine"
package_dir: "/package"
steps:
- apk add git zip wget
- mkdir -p /package/usr/share/gnome-shell/extensions
- mkdir -p /package/etc/dconf/profile
- mkdir -p /package/etc/dconf/db/local.d/

# Statusbar
- git clone https://github.com/ubuntu/gnome-shell-extension-appindicator /package/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com

# dash to panel
- wget https://github.com/home-sweet-gnome/dash-to-panel/releases/download/{{.Values.dashtoclock}}/dash-to-panel@jderose9.github.com_{{.Values.dashtoclock}}.zip
- mkdir dash-to-panel@jderose9.github.com
- mv dash-to-panel@jderose9.github.com_{{.Values.dashtoclock}}.zip dash-to-panel@jderose9.github.com
- cd dash-to-panel@jderose9.github.com && unzip dash-to-panel@jderose9.github.com_{{.Values.dashtoclock}}.zip && rm dash-to-panel@jderose9.github.com_{{.Values.dashtoclock}}.zip
- mv dash-to-panel@jderose9.github.com /package/usr/share/gnome-shell/extensions

- cp -rf user /package/etc/dconf/profile/
- cp -rf cursor /package/etc/dconf/db/local.d/00-cursor
- cp -rf extensions /package/etc/dconf/db/local.d/00-extensions
- cp -rf mocaccino /package/etc/dconf/db/local.d/01-mocaccino
