image: "ubuntu:23.04"

prelude:
- apt-get update
- apt-get install -y yarn cmake gjs ninja-build git meson
- git clone https://github.com/vixalien/sticky.git --recurse-submodules
- cd sticky && git checkout 9a750614323e630547443c3f10c67311630f58b0 && meson build
steps:
- cd sticky && ninja -C build install
