includes:
- ^/usr/share/pixmaps/designer6.png
- ^/usr/share/applications/designer6-qttools-6.desktop
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateConfigVersionImpl.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateDependencies.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateTargets.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateVersionlessAliasTargets.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateVersionlessTargets.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateAdditionalTargetInfo.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateConfig.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateConfigVersion.cmake
- ^/usr/lib64/cmake/Qt6DesignerComponentsPrivate/Qt6DesignerComponentsPrivateTargets-relwithdebinfo.cmake
- ^/usr/lib64/cmake/Qt6Designer
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerVersionlessTargets.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6QQuickWidgetPluginConfig.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerAdditionalTargetInfo.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerDependencies.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerVersionlessAliasTargets.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerConfigVersionImpl.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerPlugins.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6QQuickWidgetPluginTargets-relwithdebinfo.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6QQuickWidgetPluginConfigVersionImpl.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6QQuickWidgetPluginTargets.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerConfig.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerConfigVersion.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6QQuickWidgetPluginConfigVersion.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerTargets-relwithdebinfo.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6DesignerTargets.cmake
- ^/usr/lib64/cmake/Qt6Designer/Qt6QQuickWidgetPluginAdditionalTargetInfo.cmake
- ^/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri
- ^/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri
- ^/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri
- ^/usr/lib64/qt6/modules/Designer.json
- ^/usr/lib64/qt6/modules/DesignerComponentsPrivate.json
- ^/usr/lib64/qt6/plugins/designer
- ^/usr/lib64/qt6/plugins/designer/libqquickwidget.so
- ^/usr/lib64/qt6/bin/designer
- ^/usr/lib64/qt6/metatypes/qt6designer_relwithdebinfo_metatypes.json
- ^/usr/lib64/qt6/metatypes/qt6designercomponentsprivate_relwithdebinfo_metatypes.json
- ^/usr/lib64/pkgconfig/Qt6Designer.pc
- ^/usr/lib64/libQt6DesignerComponents.so.6.8.2
- ^/usr/lib64/libQt6Designer.prl
- ^/usr/lib64/libQt6Designer.so.6.8.2
- ^/usr/lib64/libQt6DesignerComponents.so.6
- ^/usr/lib64/libQt6Designer.so.6
- ^/usr/lib64/libQt6DesignerComponents.prl
- ^/usr/lib64/libQt6DesignerComponents.so
- ^/usr/lib64/libQt6Designer.so
- ^/usr/bin/designer6
- ^/usr/include/qt6/QtDesigner
- ^/usr/include/qt6/QtDesigner/abstractpropertyeditor.h
- ^/usr/include/qt6/QtDesigner/qdesigner_components.h
- ^/usr/include/qt6/QtDesigner/QDesignerLayoutDecorationExtension
- ^/usr/include/qt6/QtDesigner/QDesignerResourceBrowserInterface
- ^/usr/include/qt6/QtDesigner/QDesignerOptionsPageInterface
- ^/usr/include/qt6/QtDesigner/sdk_global.h
- ^/usr/include/qt6/QtDesigner/QDesignerFormWindowToolInterface
- ^/usr/include/qt6/QtDesigner/container.h
- ^/usr/include/qt6/QtDesigner/abstractpromotioninterface.h
- ^/usr/include/qt6/QtDesigner/dynamicpropertysheet.h
- ^/usr/include/qt6/QtDesigner/qextensionmanager.h
- ^/usr/include/qt6/QtDesigner/taskmenu.h
- ^/usr/include/qt6/QtDesigner/QDesignerCustomWidgetInterface
- ^/usr/include/qt6/QtDesigner/abstractformwindow.h
- ^/usr/include/qt6/QtDesigner/customwidget.h
- ^/usr/include/qt6/QtDesigner/QDesignerContainerExtension
- ^/usr/include/qt6/QtDesigner/abstractformeditorplugin.h
- ^/usr/include/qt6/QtDesigner/QDesignerLanguageExtension
- ^/usr/include/qt6/QtDesigner/QDesignerPromotionInterface
- ^/usr/include/qt6/QtDesigner/abstractactioneditor.h
- ^/usr/include/qt6/QtDesigner/abstractformwindowtool.h
- ^/usr/include/qt6/QtDesigner/QDesignerCustomWidgetCollectionInterface
- ^/usr/include/qt6/QtDesigner/QDesignerFormWindowCursorInterface
- ^/usr/include/qt6/QtDesigner/QDesignerIntegration
- ^/usr/include/qt6/QtDesigner/QDesignerMetaDataBaseInterface
- ^/usr/include/qt6/QtDesigner/QDesignerNewFormWidgetInterface
- ^/usr/include/qt6/QtDesigner/QDesignerWidgetDataBaseInterface
- ^/usr/include/qt6/QtDesigner/abstractnewformwidget.h
- ^/usr/include/qt6/QtDesigner/abstractoptionspage.h
- ^/usr/include/qt6/QtDesigner/QDesignerFormWindowInterface
- ^/usr/include/qt6/QtDesigner/QDesignerFormWindowManagerInterface
- ^/usr/include/qt6/QtDesigner/qtdesignerversion.h
- ^/usr/include/qt6/QtDesigner/extension.h
- ^/usr/include/qt6/QtDesigner/propertysheet.h
- ^/usr/include/qt6/QtDesigner/QDesignerSettingsInterface
- ^/usr/include/qt6/QtDesigner/QExtensionManager
- ^/usr/include/qt6/QtDesigner/QFormBuilder
- ^/usr/include/qt6/QtDesigner/QtDesigner
- ^/usr/include/qt6/QtDesigner/abstractlanguage.h
- ^/usr/include/qt6/QtDesigner/membersheet.h
- ^/usr/include/qt6/QtDesigner/QDesignerComponents
- ^/usr/include/qt6/QtDesigner/QDesignerIntegrationInterface
- ^/usr/include/qt6/QtDesigner/QExtensionFactory
- ^/usr/include/qt6/QtDesigner/formbuilder.h
- ^/usr/include/qt6/QtDesigner/qdesigner_components_global.h
- ^/usr/include/qt6/QtDesigner/QAbstractExtensionFactory
- ^/usr/include/qt6/QtDesigner/QDesignerFormEditorPluginInterface
- ^/usr/include/qt6/QtDesigner/QDesignerWidgetBoxInterface
- ^/usr/include/qt6/QtDesigner/QDesignerWidgetFactoryInterface
- ^/usr/include/qt6/QtDesigner/QtDesignerVersion
- ^/usr/include/qt6/QtDesigner/abstractdnditem.h
- ^/usr/include/qt6/QtDesigner/abstractintegration.h
- ^/usr/include/qt6/QtDesigner/abstractmetadatabase.h
- ^/usr/include/qt6/QtDesigner/QDesignerActionEditorInterface
- ^/usr/include/qt6/QtDesigner/QDesignerDnDItemInterface
- ^/usr/include/qt6/QtDesigner/extension_global.h
- ^/usr/include/qt6/QtDesigner/extrainfo.h
- ^/usr/include/qt6/QtDesigner/abstractobjectinspector.h
- ^/usr/include/qt6/QtDesigner/default_extensionfactory.h
- ^/usr/include/qt6/QtDesigner/uilib_global.h
- ^/usr/include/qt6/QtDesigner/abstractformbuilder.h
- ^/usr/include/qt6/QtDesigner/abstractsettings.h
- ^/usr/include/qt6/QtDesigner/QAbstractExtensionManager
- ^/usr/include/qt6/QtDesigner/QDesignerPropertyEditorInterface
- ^/usr/include/qt6/QtDesigner/6.8.2
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_promotion_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/sheet_delegate_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/spacer_widget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/abstractintrospection_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/pluginmanager_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/previewmanager_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_widget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qlayout_widget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qtresourceview_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/selectsignaldialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/layoutinfo_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/promotionmodel_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_propertysheet_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_taskmenu_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_utils_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qtresourceeditordialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/resourcebuilder_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/textbuilder_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/csshighlighter_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/plugindialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_promotiondialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/previewconfigurationwidget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qtresourcemodel_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/shared_enums_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/widgetdatabase_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/morphmenu_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/propertylineedit_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/shared_settings_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_toolbar_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/textpropertyeditor_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/actionprovider_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/deviceprofile_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_objectinspector_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/htmlhighlighter_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/plaintexteditor_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_command_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_dnditem_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_menubar_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/actioneditor_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/connectionedit_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/dialoggui_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_introspection_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_propertyeditor_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_qsettings_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_stackedbox_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/richtexteditor_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/actionrepository_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/formbuilderextra_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/layout_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/shared_global_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/properties_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_command2_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/stylesheeteditor_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/iconloader_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/orderdialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/promotiontaskmenu_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_toolbox_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/ui4_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/zoomwidget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/grid_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/gridpanel_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_formbuilder_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/rcc_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/abstractdialoggui_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_formwindowcommand_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_widgetitem_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/iconselector_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_formwindowmanager_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/signalslotdialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/widgetfactory_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/formlayoutmenu_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_tabwidget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qsimpleresource_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/extensionfactory_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/formwindowbase_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/newformwidget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_menu_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_widgetbox_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/metadatabase_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/newactiondialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_membersheet_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_formeditorcommand_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/codedialog_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/invisible_widget_p.h
- ^/usr/include/qt6/QtDesigner/6.8.2/QtDesigner/private/qdesigner_dockwidget_p.h
- ^/usr/include/qt6/QtDesigner/abstractwidgetbox.h
- ^/usr/include/qt6/QtDesigner/QDesignerMetaDataBaseItemInterface
- ^/usr/include/qt6/QtDesigner/QDesignerWidgetDataBaseItemInterface
- ^/usr/include/qt6/QtDesigner/abstractformwindowmanager.h
- ^/usr/include/qt6/QtDesigner/abstractwidgetfactory.h
- ^/usr/include/qt6/QtDesigner/QAbstractFormBuilder
- ^/usr/include/qt6/QtDesigner/QDesignerFormEditorInterface
- ^/usr/include/qt6/QtDesigner/QDesignerObjectInspectorInterface
- ^/usr/include/qt6/QtDesigner/QDesignerPropertySheetExtension
- ^/usr/include/qt6/QtDesigner/QDesignerTaskMenuExtension
- ^/usr/include/qt6/QtDesigner/QtDesignerDepends
- ^/usr/include/qt6/QtDesigner/abstractformeditor.h
- ^/usr/include/qt6/QtDesigner/abstractformwindowcursor.h
- ^/usr/include/qt6/QtDesigner/QDesignerDynamicPropertySheetExtension
- ^/usr/include/qt6/QtDesigner/QDesignerExportWidget
- ^/usr/include/qt6/QtDesigner/qdesignerexportwidget.h
- ^/usr/include/qt6/QtDesigner/abstractresourcebrowser.h
- ^/usr/include/qt6/QtDesigner/abstractwidgetdatabase.h
- ^/usr/include/qt6/QtDesigner/layoutdecoration.h
- ^/usr/include/qt6/QtDesigner/QDesignerExtraInfoExtension
- ^/usr/include/qt6/QtDesigner/QDesignerMemberSheetExtension
- ^/usr/include/qt6/QtDesignerComponents
- ^/usr/include/qt6/QtDesignerComponents/QtDesignerComponentsDepends
- ^/usr/include/qt6/QtDesignerComponents/QtDesignerComponentsVersion
- ^/usr/include/qt6/QtDesignerComponents/qtdesignercomponentsversion.h
- ^/usr/include/qt6/QtDesignerComponents/6.8.2
- ^/usr/include/qt6/QtDesignerComponents/6.8.2/QtDesignerComponents
- ^/usr/include/qt6/QtDesignerComponents/6.8.2/QtDesignerComponents/private
- ^/usr/include/qt6/QtDesignerComponents/6.8.2/QtDesignerComponents/private/lib_pch.h
- ^/usr/include/qt6/QtDesignerComponents/QtDesignerComponents
excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "qt"
  version: ">=0"
