excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- emerge -1 app-eselect/eselect-ruby && sed -i "s/^RUBY_TARGETS=.*/RUBY_TARGETS=\"ruby$(eselect ruby list --brief | tail -n1 | grep -oE '[0-9]{2}')\"/" /etc/portage/make.conf
{{ template "portage_copy_package_files" . }}
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
