excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.unmask /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- FEATURES="${FEATURES} binpkg-request-signature" emerge -g net-libs/webkit-gtk:4.1 net-libs/webkit-gtk:6
- rm -rf /etc/portage/gnupg
- rm -r /var/cache/binpkgs/*
- emerge -1 gnome-extra/zenity net-libs/gnome-online-accounts gnome-extra/evolution-data-server
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
