excludes:
{{ template "portage_excludes" }}

env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
# workaround that can be removed once package.env is a directory created from system-x
- if test -f "/etc/portage/package.env" ; then rm "/etc/portage/package.env"; fi
- cp -rf package.env /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- etc-update -q --automode -5
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
