excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.unmask /etc/portage/
{{ template "portage_prelude_build" . }}
# template start
- |
  FEATURES="${FEATURES} binpkg-request-signature" EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --getbinpkg" emerge -j ${JOBS} --onlydeps --onlydeps-with-rdeps n {{ ( index .Values.labels "emerge.packages" ) }} && \
  emerge -C {{ ( index .Values.labels "emerge.packages" ) }} || true && \
  /bin/sh -c 'find /usr -xtype l 2>/dev/null -exec rm -v {} \;'
- rm -rf /etc/portage/gnupg
- rm -r /var/cache/binpkgs/*
# template end
steps:
# template start
- FEATURES="${FEATURES} binpkg-request-signature" EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --getbinpkg" emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- rm -rf /etc/portage/gnupg
- rm -r /var/cache/binpkgs/*
- etc-update -q --automode -5
# template end
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
