excludes:
{{ template "portage_excludes" }}
- ^/run
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf patches /etc/portage/
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
