excludes:
{{ template "portage_excludes" }}
- ^/run
- ^/etc/openldap/ssl/ldap.*
- ^/etc/sasl2/sasldb2
- ^/etc/plymouth/plymouthd.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.license /etc/portage/
- cp -rf patches /etc/portage/
- USE="inspector profiler rustfmt" emerge -1 dev-lang/rust virtual/rust
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build_gentoo_binary" . }}
# Fix plymouth service file
- sed -i '/^ConditionVirtualization.*/a IgnoreOnIsolate=true' /lib/systemd/system/plymouth-start.service
- sed -i -e 's/KillMode=none/KillMode=mixed/g' /lib/systemd/system/plymouth-start.service
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
