excludes:
{{ template "portage_excludes" }}
- ^/run
- ^/etc/openldap/ssl/ldap.*
- ^/etc/sasl2/sasldb2
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.license /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf patches /etc/portage/
- USE="inspector profiler rustfmt" emerge -1 dev-lang/rust-bin
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build_gentoo_binary" . }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
