excludes:
{{ template "portage_excludes" }}
- ^/run
- ^/etc/openldap/ssl/ldap.*
- ^/etc/sasl2/sasldb2
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.license /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf patches /etc/portage/
- USE="inspector profiler rustfmt" emerge -1 dev-lang/rust-bin
- emerge -1 dev-util/ccache
# We grab some binary packages to prevent pulling in dev-python/pillow through dev-python/docutils
# dev-python/pillow is merged downstream in layers/X
- EMERGE_DEFAULT_OPTS="--getbinpkg --quiet" emerge -1 dev-util/gdbus-codegen
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
# Clean up binary cache (we are not using the template for binaries
- if [ -d /var/cache/binpkgs/ ] && [ ! -z "$(ls -A /var/cache/binpkgs/)" ]; then rm -r /var/cache/binpkgs/*; fi
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
