excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- emerge -1 x11-themes/gnome-themes-standard x11-themes/adwaita-icon-theme
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
