excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 x11-themes/gnome-themes-standard x11-themes/adwaita-icon-theme
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
# Be sure to remove these BDEPS they are shipped in C-R and cause a collision otherwise.
# Once we do not require llvm:14 anymore (required by dev-lang/spidermonkey:78 )
- emerge -C sys-devel/clang:14 sys-devel/clang-common:14 sys-devel/clang-runtime:14 sys-devel/llvm:14 sys-libs/compiler-rt:14 compiler-rt-sanitizers:14 && emerge --depclean
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
