# $ARCH can't be amd64 here, x86_64 is used here
{{$arch := ""}}
{{if eq .Values.arch "amd64" }}
{{$arch = "x86_64"}}
{{end}}
steps:
- cp -rfv output/boot/* /luetbuild/modules/boot
package_dir: /luetbuild/modules
requires:
- name: "mocaccino-modules"
  category: "kernel"
  version: ">=0"
includes:
# Kernel
- /boot$
- /boot/{{ .Values.kernelprefix }}-{{ $arch }}-{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}$
- /boot/System.map-.*-{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}$

- /usr/lib$
- /usr/lib/modules$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/modules.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/source
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/build

# OverlayFS
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/mbcache.ko
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/overlayfs$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/overlayfs/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/lib$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/lib/.*

# Crypto
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/crypto$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/crypto/.*

# EXT
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/ext2$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/ext4$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/jbd2$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/ext2/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/ext4/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/fs/jbd2/.*

# USB
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb/storage$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb/storage/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb/host$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb/host/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb/common$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/usb/common/.*

- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/hid$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/hid/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/hid/usbhid$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/hid/usbhid/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/hid/i2c-hid$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/hid/i2c-hid/.*


# Input
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input/keyboard$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input/keyboard/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input/misc$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input/misc/.*
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input/mouse$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/input/mouse/.*

# block
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/block$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/block/.*

# ATA
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/ata$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/ata/.*

# md
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/md$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/md/.*

# firewire
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/firewire$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/firewire/.*

# virtio
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/virtio$
- /usr/lib/modules/{{ ( index .Values.labels "package.version" ) }}-{{ .Values.suffix }}/kernel/drivers/virtio/.*
