image: "alpine"
package_dir: "/package"
steps:
- wget -O BlackSun.tar.gz https://github.com/SethStormR/Black-Sun/raw/refs/heads/main/Black%20Sun.tar.gz
- mkdir -p /package/usr/share/icons
- tar -xvzf BlackSun.tar.gz -C /package/usr/share/icons --strip-components=1
