image: "alpine"
prelude:
- wget -O BlackSun.tar.gz https://github.com/SethStormR/Black-Sun/raw/refs/heads/main/Black%20Sun.tar.gz
steps:
- mkdir -p /usr/share/icons
- tar -xvzf BlackSun.tar.gz -C /usr/share/icons --strip-components=1
