excludes:
{{ template "portage_excludes" }}
#TODO: Why is this service file here?
- ^/usr/lib/systemd/system/pam_namespace.service
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
requires:
- category: "layers"
  name: "X"
  version: ">=0"
