excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.license /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable steam-overlay
- emaint sync -r steam-overlay
steps:
{{ template "portage_build" . }}
- eselect repository remove steam-overlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
