excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.license /etc/portage/
- emerge -C x11-misc/notification-daemon
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build_gentoo_binary" . }}
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
