{{ if eq .Values.name "firmware" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- emerge -1 media-video/isight-firmware-tools
- cp AppleUSBVideoSupport /tmp
steps:
- mkdir -p /usr/lib/firmware/isight
- ift-extract --apple-driver /tmp/AppleUSBVideoSupport
- rm /tmp/AppleUSBVideoSupport
{{ template "portage_build" . }}
# split nvidia-gsp stuff 
- mkdir -p /usr/lib/firmware/nvidia-gsp && for gpu in ad102 ga100 ga102 gb100 gb202 gh100 tu102 tu116; do mkdir -p /usr/lib/firmware/nvidia-gsp/$gpu && mv /usr/lib/firmware/nvidia/$gpu/gsp /usr/lib/firmware/nvidia-gsp/$gpu/ || true; done
- for gpu in ad102 ga100 ga102 gb100 gb202 gh100 tu102 tu116; do mkdir -p /usr/lib/firmware/nvidia/$gpu && ln -s ../../../nvidia-gsp/$gpu/gsp /usr/lib/firmware/nvidia/$gpu/gsp || true; done
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
includes:
- ^/usr/lib/firmware/.*\..*
excludes:
- ^/usr/lib/firmware/.*/.*
{{ template "portage_excludes" }}
{{ else }}
requires:
- category: "layers"
  name: "firmware"
  version: ">=0"
steps:
- echo "Splitting {{ trimPrefix "firmware-" .Values.name }}"
unpack: true
includes:
- ^/usr/lib/firmware/{{ trimPrefix "firmware-" .Values.name }}/.*
excludes:
{{ template "portage_excludes" }}
{{ end }}
