excludes:
{{ template "portage_excludes" }}

env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.license /etc/portage/
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
