{{ if eq .Values.name "firmware" }}
env:
{{ template "portage_env" . }}
prelude:
- wget https://gitweb.gentoo.org/repo/gentoo.git/plain/sys-kernel/linux-firmware/linux-firmware-20250808.ebuild /var/db/repos/gentoo/sys-kernel/linux-firmware/linux-firmware-20250808.ebuild
- ebuild /var/db/repos/gentoo/sys-kernel/linux-firmware/linux-firmware-20250808.ebuild manifest
{{ template "portage_copy_package_files" . }}
- emerge -1 media-video/isight-firmware-tools
- cp AppleUSBVideoSupport /tmp
steps:
- mkdir -p /usr/lib/firmware/isight
- ift-extract --apple-driver /tmp/AppleUSBVideoSupport
- rm /tmp/AppleUSBVideoSupport
{{ template "portage_build" . }}
# split nvidia-gsp-570 stuff (introduced in linux-firmware commit 050f0a1)
- mkdir -p /usr/lib/firmware/nvidia-gsp-570 && find /usr/lib/firmware/nvidia -type f -path '*/gsp/*-570.144.bin' -exec sh -c 'for f; do gpu=$(echo "$f" | cut -d/ -f6); mkdir -p "/usr/lib/firmware/nvidia-gsp-570/$gpu/gsp"; mv "$f" "/usr/lib/firmware/nvidia-gsp-570/$gpu/gsp/"; done' sh {} +
- find /usr/lib/firmware/nvidia-gsp-570 -type f -path '*/gsp/*-570.144.bin' -exec sh -c 'for f; do gpu=$(echo "$f" | cut -d/ -f6); mkdir -p "/usr/lib/firmware/nvidia/$gpu/gsp"; ln -sf "../../../nvidia-gsp-570/$gpu/gsp/$(basename "$f")" "/usr/lib/firmware/nvidia/$gpu/gsp/"; done' sh {} +
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
includes:
- ^/usr/lib/firmware/.*\..*
excludes:
- ^/usr/lib/firmware/.*/.*
{{ template "portage_excludes" }}
{{ else }}
requires:
- category: "layers"
  name: "firmware"
  version: ">=0"
steps:
- echo "Splitting {{ trimPrefix "firmware-" .Values.name }}"
unpack: true
includes:
- ^/usr/lib/firmware/{{ trimPrefix "firmware-" .Values.name }}/.*
excludes:
{{ template "portage_excludes" }}
{{ end }}
