env:
excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
prelude:
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.license /etc/portage/
- emerge -1 media-fonts/fira-mono media-fonts/fira-sans
- emerge -1 app-eselect/eselect-repository
- emerge -1 app-misc/geoclue
- eselect repository add cosmic-overlay git https://github.com/fsvm88/cosmic-overlay
- emaint sync -r cosmic-overlay
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove -f cosmic-overlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
