env:
excludes:
{{ template "portage_excludes" }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
# No need for mold yet in this phase of testing
# - emerge -1 app-eselect/eselect-repository && eselect repository enable guru && emaint sync -r guru
# - emerge -1 dev-build/just && emerge -1 sys-devel/mold
# TODO: Later combine this with flatpak layer
- emerge -1 sys-apps/flatpak media-fonts/fira-mono media-fonts/fira-sans
- emerge -1 app-eselect/eselect-repository
- eselect repository add cosmic-overlay git https://github.com/fsvm88/cosmic-overlay
- emaint sync -r cosmic-overlay
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove cosmic-overlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "wlroots"
  version: ">=0"
