env:
- LIBCLANG_PATH="/usr/lib/llvm/17/lib64"
- LLVM_CONFIG_PATH="/usr/lib/llvm/17/bin/llvm-config"
- CARGO_BUILD_JOBS=10
excludes:
{{ template "portage_excludes" }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository && eselect repository enable guru && emaint sync -r guru
- emerge -1 dev-build/just && emerge -1 sys-devel/mold
# TODO: Later combine this with flatpak layer
- emerge -1 sys-apps/flatpak
- |
    pkglist=( cosmic-session cosmic-applets cosmic-applibrary cosmic-comp cosmic-launcher cosmic-notifications cosmic-panel cosmic-randr cosmic-screenshot cosmic-settings-daemon cosmic-settings cosmic-workspaces-epoch )
    for pkgname in "${pkglist[@]}"
    do
        echo "debug: loop $pkgname"
        RUSTFLAGS="-A warnings -C link-arg=-fuse-ld=mold" git clone --recurse-submodules https://github.com/pop-os/"$pkgname" && \
        cd "$pkgname" && \
        if [ $pkgname == "cosmic-session" ]; then
            nice just all && \
        elif [ $pkgname == "cosmic-comp"  || $pkgname == "cosmic-settings-daemon" || $pkgname == "cosmic-workspaces-epoch" ]; then
            make vendor && \
            nice make VENDOR='1' all && \       
        elif [ $pkgname == "cosmic-icons" ]; then
            nice just build-release && \            
        else
            just vendor && \
            nice just build-vendored && \
        fi
        cd .. && \
    done
#- |
#    RUSTFLAGS="-A warnings -C link-arg=-fuse-ld=mold" git clone --recurse-submodules https://github.com/pop-os/cosmic-bg && \
#    cd cosmic-bg && \
#    just vendor && \
#    nice just build-vendored
#- |
#    RUSTFLAGS="-A warnings -C link-arg=-fuse-ld=mold" git clone --recurse-submodules https://github.com/pop-os/cosmic-greeter && \
#    cd cosmic-greeter && \
#    just vendor && \
#    nice just build-vendored
steps:
- cd cosmic-session && just install
- cd cosmic-applets && just install
- cd cosmic-applibrary && just install
#- cd cosmic-bg && just install
- cd cosmic-comp && make install
#- cd cosmic-greeter && just install
- cd cosmic-icons && just install
- cd cosmic-launcher && just install
- cd cosmic-notifications && just install
- cd cosmic-panel && just install
- cd cosmic-randr && just install
- cd cosmic-screenshot && just install
- cd cosmic-settings-daemon && make prefix='/usr' install
- cd cosmic-settings && just install
- cd cosmic-workspaces-epoch && make prefix='/usr' install
requires:
- category: "layers"
  name: "wlroots"
  version: ">=0"
