env:
- LIBCLANG_PATH="/usr/lib/llvm/17/lib64"
- LLVM_CONFIG_PATH="/usr/lib/llvm/17/bin/llvm-config"
# - CARGO_BUILD_JOBS=10
- RUSTFLAGS="-Z threads=8 -A warnings -C link-arg=-fuse-ld=mold"
excludes:
{{ template "portage_excludes" }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository && eselect repository enable guru && emaint sync -r guru
- emerge -1 dev-build/just && emerge -1 sys-devel/mold
# TODO: Later combine this with flatpak layer
- emerge -1 sys-apps/flatpak
- |
    git clone --recurse-submodules https://github.com/pop-os/cosmic-session && \
    cd cosmic-session && \
    nice just all
- |
    git clone --recurse-submodules https://github.com/pop-os/cosmic-applets && \
    cd cosmic-applets && \
    just vendor && \
    nice just build-vendored
- |
    git clone --recurse-submodules https://github.com/pop-os/cosmic-applibrary && \
    cd cosmic-applibrary && \
    just vendor && \
    nice just build-vendored
steps:
- cd cosmic-session && just install
- cd cosmic-applets && just install
- cd cosmic-applibrary && just install
requires:
- category: "layers"
  name: "wlroots"
  version: ">=0"
