excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
prelude:
{{ template "portage_copy_package_files" . }}
- cp -rf env /etc/portage/
- emerge -1 media-fonts/fira-mono media-fonts/fira-sans
- emerge -1 app-eselect/eselect-repository
- eselect repository add cosmic-overlay git https://github.com/fsvm88/cosmic-overlay
- emaint sync -r cosmic-overlay
- emerge -C dev-lang/rust-bin && emerge -1 dev-lang/rust
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove -f cosmic-overlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
