prelude:
- git clone https://gitlab.gnome.org/World/amberol.git
- cd amberol && meson build
steps:
- cd amberol && ninja -C build install
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
