excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "apps"
  name: "spice-gtk"
  version: ">=0"
- category: "layers"
  name: "gnome-common"
  version: ">=0"
