excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
- mkdir -p /var/db/repos/gentoo/app-admin/calamares
- cd /var/db/repos/gentoo/app-admin/calamares && wget https://raw.githubusercontent.com/gentoo/gentoo/master/app-admin/calamares/calamares-3.2.60-r2.ebuild
- cd /var/db/repos/gentoo/app-admin/calamares && mv calamares-3.2.60-r2.ebuild calamares-3.2.62.ebuild
- ebuild /var/db/repos/gentoo/app-admin/calamares/calamares-3.2.62.ebuild manifest
steps:
{{ template "portage_build" . }}
- cp 49-calamares.rules /usr/share/polkit-1/rules.d/
- chown 102:0 /usr/share/polkit-1/rules.d/49-calamares.rules
- chmod 700 /usr/share/polkit-1/rules.d/49-calamares.rules
requires:
- category: "buildbase"
  name: "kde-common"
  version: ">=0"
- category: "buildbase"
  name: "grub"
  version: ">=0"
requires_final_images: true
