excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.mask /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable thegreatmcpain
- emaint sync -r thegreatmcpain
# needed for hyprpaper
- eselect repository enable wayland-desktop
- emaint sync -r wayland-desktop
# needed for clipman
- eselect repository enable guru
- emaint sync -r guru
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove thegreatmcpain wayland-desktop guru
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
