excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable thegreatmcpain
- emaint sync -r thegreatmcpain
# needed for hyprpaper
- eselect repository enable wayland-desktop
- emaint sync -r wayland-desktop
# needed for clipman
- eselect repository enable guru
- emaint sync -r guru
# {{ template "portage_prelude_build" . }}
# clipman upstream git repo got removed, grab sources here
# see https://www.reddit.com/r/swaywm/comments/16v6eat/clipman_repository_has_disappeared/
- mkdir -p /usr/portage/distfiles/ && wget https://github.com/chmouel/clipman/archive/refs/tags/v1.6.2.tar.gz -O /usr/portage/distfiles/clipman-1.6.2.tar.gz
- ebuild /var/db/repos/guru/gui-apps/clipman/clipman-1.6.2.ebuild manifest
steps:
{{ template "portage_build" . }}
- eselect repository remove thegreatmcpain wayland-desktop guru
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "wlroots"
  version: ">=0"
