excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
# needed for hyprpaper
- eselect repository enable wayland-desktop
- emaint sync -r wayland-desktop
# needed for clipman
- eselect repository enable guru
- emaint sync -r guru
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove wayland-desktop guru
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
