excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- USE="-subversion -mercurial" emerge app-portage/layman
- layman -L
- echo "y" | layman -a thegreatmcpain
# needed for hyprpaper
- echo "y" | layman -a wayland-desktop
# needed for clipman
- echo "y" | layman -a guru
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- emerge -C dev-lang/go dev-lang/go-bootstrap dev-libs/oniguruma app-misc/jq app-portage/layman dev-python/ssl-fetch
requires:
- category: "layers"
  name: "wlroots"
  version: ">=0"
