excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable haarp
- emaint sync -r haarp
- cp /var/db/repos/haarp/app-editors/xed/xed-3.4.5.ebuild /var/db/repos/haarp/app-editors/xed/xed-3.8.1.ebuild
- sed -i 's/python3_{11..12}/python3_{11..13}/' /var/db/repos/haarp/app-editors/xed/xed-3.8.1.ebuild
- ebuild /var/db/repos/haarp/app-editors/xed/xed-3.4.5.ebuild manifest
- eselect repository enable binaryden
- emaint sync -r binaryden
steps:
{{ template "portage_build" . }}
- eselect repository remove steam-overlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "cinnamon"
  version: ">=0"
