excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.unmask /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable SarahMiaOverlay
- emaint sync -r SarahMiaOverlay
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- eselect repository remove SarahMiaOverlay
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "gnome"
  version: ">=0"
