excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
# Because of a PDEPEND we need to have this installed in the build chroot
- USE="gtk" emerge -1 sys-auth/polkit
{{ template "portage_copy_package_files" . }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable Miezhiko
- emaint sync -r Miezhiko
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "apps"
  name: "apparmor"
  version: ">=0"
