includes:
{{ if contains "system-x" .Values.name }}
- /etc/portage/.*
{{- end}}
- /usr$
- /usr/include$
- /usr/include/.*
- /usr/lib/python3.13/test
unpack: true
requires:
- name: {{.Values.package}}
  version: ">=0"
  category: layers
