excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
- cp -rf package.use /etc/portage/
steps:
- groupadd -g 219 sddm
- useradd -g 219 -u 219 sddm
- mkdir -p /var/lib/sddm/.config
- touch /var/lib/sddm/.config/.keep
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- sed -i 's/Gentoo Linux/MocaccinoOS/g' /etc/xdg/kcm-about-distrorc
- sed -i 's/www.gentoo.org/www.mocaccino.org/g' /etc/xdg/kcm-about-distrorc
- sed -i 's/kinfocenter\/glogo-small.png/icons\/mOS-icons\/mOS_outlined_hl.png/g' /etc/xdg/kcm-about-distrorc
- emerge -C dev-libs/check
- chown -R 219:219 /var/lib/sddm
- etc-update -q --automode -5
requires:
- category: "layers"
  name: "kde-common"
  version: ">=0"
- category: "apps"
  name: "vlc"
  version: ">=0"
