excludes:
{{ template "portage_excludes" }}
# To reduce footprint drop some wallpapers, they can be installed through themes/plasma-wallpapers-extra
- ^/usr/share/wallpapers/Autumn
- ^/usr/share/wallpapers/Canopee
- ^/usr/share/wallpapers/ColdRipple
- ^/usr/share/wallpapers/FlyingKonqui
- ^/usr/share/wallpapers/Grey
- ^/usr/share/wallpapers/Kite
- ^/usr/share/wallpapers/Mountain
- ^/usr/share/wallpapers/OneStandsOut
- ^/usr/share/wallpapers/Path
- ^/usr/share/wallpapers/SafeLanding
- ^/usr/share/wallpapers/ScarletTree
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- sed -i 's/Gentoo Linux/MocaccinoOS/g' /etc/xdg/kcm-about-distrorc
- sed -i 's/www.gentoo.org/www.mocaccino.org/g' /etc/xdg/kcm-about-distrorc
- sed -i 's/kinfocenter\/glogo-small.png/icons\/mOS-icons\/mOS_outlined_hl.png/g' /etc/xdg/kcm-about-distrorc
- cp -r 01gentoo.conf /etc/sddm.conf.d/01gentoo.conf
# We do not require to force SDDM in Wayland mode. Old workaround for ARC that is now fixed in a proper detection code.
# - cp -r 10-wayland.conf /etc/sddm.conf.d/10-wayland.conf
requires:
- category: "layers"
  name: "kde-common"
  version: ">=0"
