includes:
# portage_excludes template
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/usr/tmp/portage
- ^/usr/lib/cmake
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
# Excluded from layers/system-x
- ^/etc/portage
# Emerge/portage
- ^/usr/bin/emerge
- ^/usr/bin/emerge-webrsync
- ^/usr/sbin/dispatch-conf
- ^/etc/dispatch-conf.conf
- ^/usr/lib/python-exec/python.*/dispatch-conf
- ^/usr/share/man/man1/dispatch-conf.1.bz2
- ^/usr/share/man/man1/emerge.1.bz2
env:
{{ template "portage_env" . }}
steps:
{{ template "portage_build" . }}
unpack: true
requires:
- category: "layers"
  name: "system-x"
  version: ">=0"
