excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
# Try last known to work version
- cp gnome-software-42.1.ebuild /var/db/repos/gentoo/gnome-extra/gnome-software
- ebuild /var/db/repos/gentoo/gnome-extra/gnome-software/gnome-software-42.1.ebuild manifest
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "buildbase"
  name: "gnome-common"
  version: ">=0"
- category: "buildbase"
  name: "flatpak"
  version: ">=0"
requires_final_images: true
