excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- mkdir /var/db/repos/gentoo/gnome-extra/gnome-software
- cd /var/db/repos/gentoo/gnome-extra/gnome-software && wget https://raw.githubusercontent.com/gentoo/gentoo/e6780323b71c7a6a72f7942060195f04df27d2f2/gnome-extra/gnome-software/gnome-software-43.5.ebuild
- ebuild /var/db/repos/gentoo/gnome-extra/gnome-software/gnome-software-43.5.ebuild manifest
steps:
# - emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge =gnome-extra/gnome-software-43.5
requires:
- category: "buildbase"
  name: "gnome-common"
  version: ">=0"
- category: "buildbase"
  name: "flatpak"
  version: ">=0"
requires_final_images: true
