image: "quay.io/mocaccino/extra:latest"

package_dir: /gentoo

prelude:
- luet upgrade && luet install -y --force utils/tar utils/curl utils/xz
- mkdir /gentoo

steps:
# TODO: checksum

# Gentoo stage3 are broken due to https://bugs.gentoo.org/780810

- curl -L http://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-systemd/stage3-amd64-systemd-${STAGE_VERSION}.tar.xz | tar Jxp --xattrs --numeric-owner -C /gentoo

#- curl -L https://get.mocaccino.org/gentoo-stage3/stage3-amd64-systemd-20201129T214504Z.tar.xz | tar Jxp --xattrs --numeric-owner -C /gentoo

env:
- LUET_YES=true
- STAGE_VERSION={{ ( index .Values.labels "package.version" ) }}

# Add some common excludes
excludes:
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/machineid
- ^/sys
- ^/proc
