{{ if ne .Values.image "" }}
image: {{.Values.image}}
unpack: true
{{else}}
image: "alpine"

package_dir: /gentoo

prelude:
- apk add curl xz tar
- mkdir /gentoo

steps:
- curl -L http://distfiles.gentoo.org/releases/{{.Values.arch}}/autobuilds/${STAGE_VERSION}/stage3-{{.Values.arch}}-systemd-${STAGE_VERSION}.tar.xz | tar Jxp --xattrs --numeric-owner -C /gentoo

env:
{{ if ne .Values.arch "amd64"}}
- STAGE_VERSION={{ ( index .Values.labels (print "package.version." .Values.arch ) ) }}
{{ else }}
- STAGE_VERSION={{ ( index .Values.labels "package.version" ) }}
{{ end }}
{{end}}
# Add some common excludes
excludes:
- ^/etc/os-release
- ^/etc/gshadow
- ^/etc/hostname
- ^/etc/hosts
- ^/etc/machine-id
- ^/etc/machineid
- ^/sys
- ^/proc
