excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
- ^/luetbuild
- ^/etc/default/grub
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- cp -rf package.use /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- cp -r 10_linux /etc/grub.d/10_linux
# Fix plymouth service file
- sed -i '/^ConditionVirtualization.*/a IgnoreOnIsolate=true' /lib/systemd/system/plymouth-start.service
- sed -i -e 's/KillMode=none/KillMode=mixed/g' /lib/systemd/system/plymouth-start.service
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
