excludes:
{{ template "portage_excludes" }}
- ^/etc/plymouth/plymouthd.conf
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
- LUET_YES=true
- LUET_NOLOCK=true
prelude:
- cp -rf package.use /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- cp -r 10_linux /etc/grub.d/10_linux
- cp -r grub-background.png /boot/grub/grub-background.png
# Fix plymouth service file
- sed -i '/^ConditionVirtualization.*/a IgnoreOnIsolate=true' /lib/systemd/system/plymouth-start.service
- sed -i -e 's/KillMode=none/KillMode=mixed/g' /lib/systemd/system/plymouth-start.service
- sed -i -e '/GRUB_DISTRIBUTOR/ s/Gentoo/Mocaccino/' /etc/default/grub
- sed -i -e '/GRUB_CMDLINE_LINUX_DEFAULT/ s/#GRUB_CMDLINE_LINUX_DEFAULT=""/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash rd.udev.log-priority=3"/' /etc/default/grub
- sed -i -e '/GRUB_BACKGROUND/ s/#GRUB_BACKGROUND="\/boot\/grub\/mybackground.png"/GRUB_BACKGROUND="\/boot\/grub\/grub-background.png"/' /etc/default/grub
- echo -e "\nGRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
