excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
steps:
{{ template "portage_build" . }}
- cp -r mocaccino.txt /usr/share/neofetch/mocaccino.txt
- mkdir -p /etc/neofetch && cp config.txt /etc/neofetch/config.txt
requires:
- category: "layers"
  name: "X"
  version: ">=0"
