excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C dev-util/lxqt-build-tools dev-qt/qttools
requires:
- category: "layers"
  name: "qt"
  version: ">=0"
