excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C dev-util/lxqt-build-tools
requires:
- category: "layers"
  name: "qt"
  version: ">=0"
