excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
- USE="graphite" emerge -1 sys-devel/gcc
{{ template "portage_prelude_build" . }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
