excludes:
{{ template "portage_excludes" }}
# Add back once VLC4 is stable in Portage tree
- ^/usr/share/applications/phononsettings-phonon.desktop
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "buildbase"
  name: "qt"
  version: ">=0"
requires_final_images: true
