excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- USE="ogg" emerge -1 media-libs/phonon-vlc
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build_gentoo_binary" . }}
requires:
- category: "buildbase"
  name: "qt"
  version: ">=0"
requires_final_images: true
