excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf patches /etc/portage/
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository add cutefishos git https://github.com/HougeLangley/cutefishos-overlay.git
- eselect repository enable cutefishos
- emaint sync -r cutefishos
- cp libcutefish-0.7-r1.ebuild /var/db/repos/cutefishos/sys-libs/libcutefish/
- ebuild /var/db/repos/cutefishos/sys-libs/libcutefish/libcutefish-0.7-r1.ebuild manifest
# {{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove cutefishos
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "plasma"
  version: ">=0"
