image: "archlinux"

prelude:
- pacman -Syy
steps:
- pacman -Sdd --noconfirm extra/libcutefish extra/fishui extra/cutefish-core extra/cutefish-calculator extra/cutefish-dock extra/cutefish-filemanager extra/cutefish-icons extra/cutefish-kwin-plugins extra/cutefish-launcher extra/cutefish-qt-plugins extra/cutefish-screenlocker extra/cutefish-settings extra/cutefish-statusbar extra/cutefish-terminal extra/cutefish-wallpapers 
