excludes:
{{ template "portage_excludes" }}

env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C dev-util/lxqt-build-tools
- etc-update -q --automode -5
requires:
- category: "buildbase"
  name: "kde-common"
  version: ">=0"
- category: "buildbase"
  name: "pavucontrol-qt"
  version: ">=0"
requires_final_images: true
