excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- emerge -1 media-sound/pavucontrol-qt
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "kde-common"
  version: ">=0"
