excludes:
{{ template "portage_excludes" }}

env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
steps:
{{ template "portage_build" . }}
- emerge -C dev-util/lxqt-build-tools
requires:
- category: "buildbase"
  name: "kde-common"
  version: ">=0"
- category: "buildbase"
  name: "pavucontrol-qt"
  version: ">=0"
requires_final_images: true
