excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- emerge -1 media-video/vlc
steps:
- emerge kde-apps/konsolekalendar
{{ template "portage_build" . }}
requires:
- category: "layers"
  name: "plasma"
  version: ">=0"
