excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
- mkdir -p /var/lib/gdm/.config
- touch /var/lib/gdm/.config/.keep
{{ template "portage_build_gentoo_binary" . }}
- chown -R 32:32 /var/lib/gdm
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
