excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.mask /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
- mkdir -p /var/lib/gdm/.config
- touch /var/lib/gdm/.config/.keep
# template start
- FEATURES="${FEATURES} binpkg-request-signature" EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --getbinpkg" emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- rm -rf /etc/portage/gnupg
- rm -r /var/cache/binpkgs/*
- etc-update -q --automode -5
# template end
- chown -R 32:32 /var/lib/gdm
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
