excludes:
{{ template "portage_excludes" }}

env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
steps:
- groupadd -g 32 gdm
- useradd -g 32 -u 32 gdm
- mkdir -p /var/lib/gdm/.config
- touch /var/lib/gdm/.config/.keep
# Workaround needed until we sync Portage tree again (15-6-2021)
- wget https://data.gpo.zugaina.org/gentoo/net-misc/dleyna-server/dleyna-server-0.7.0-r1.ebuild -P /var/db/repos/gentoo/net-misc/dleyna-server
- ebuild /var/db/repos/gentoo/net-misc/dleyna-server/dleyna-server-0.7.0-r1.ebuild manifest
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C app-misc/jq
- chown -R 32:32 /var/lib/gdm
- etc-update -q --automode -5
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
