excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build_gentoo_binary" . }}
requires:
- category: "layers"
  name: "plasma"
  version: ">=0"
