excludes:
{{ template "portage_excludes" }}

env:
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
prelude:
- cp -rf package.use /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- etc-update -q --automode -5
requires:
- category: "layers"
  name: "plasma"
  version: ">=0"
