excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
steps:
{{ template "portage_build" . }}
- cp -r 49-calamares.rules /etc/polkit-1/rules.d/
- chown 102:0 /etc/polkit-1/rules.d/*.rules
- chmod 700 /etc/polkit-1/rules.d/*.rules
requires:
- category: "buildbase"
  name: "kde-common"
  version: ">=0"
- category: "buildbase"
  name: "grub"
  version: ">=0"
requires_final_images: true
