excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
steps:
{{ template "portage_build" . }}
- cp 49-calamares.rules /usr/share/polkit-1/rules.d/
- chown 102:0 /usr/share/polkit-1/rules.d/49-calamares.rules
- chmod 700 /usr/share/polkit-1/rules.d/49-calamares.rules
requires:
- category: "layers"
  name: "kde-common"
  version: ">=0"
- category: "apps"
  name: "grub"
  version: ">=0"
