excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- emerge -C dev-lang/python:2.7 net-libs/nodejs
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
