excludes:
{{ template "portage_excludes" }}
# Poppler split. Only ship Qt module
- ^/usr/bin/pdfattach
- ^/usr/bin/pdfdetach
- ^/usr/bin/pdffonts
- ^/usr/bin/pdfimages
- ^/usr/bin/pdfinfo
- ^/usr/bin/pdfseparate
- ^/usr/bin/pdfsig
- ^/usr/bin/pdftocairo
- ^/usr/bin/pdftohtml
- ^/usr/bin/pdftoppm
- ^/usr/bin/pdftops
- ^/usr/bin/pdftotext
- ^/usr/bin/pdfunite
- ^/usr/lib64/girepository-1.0/Poppler-0.18.typelib
- ^/usr/lib64/libpoppler-cpp.*
- ^/usr/lib64/libpoppler-glib.*
- ^/usr/lib64/libpoppler.so.*
- ^/usr/lib64/pkgconfig/poppler-cpp.pc
- ^/usr/lib64/pkgconfig/poppler-glib.pc
- ^/usr/lib64/pkgconfig/poppler.pc
- ^/usr/share/doc/poppler.*
- ^/usr/share/gir-1.0/Poppler-0.18.gir
- ^/usr/share/locale/ca/LC_MESSAGES/pdfsig.mo
- ^/usr/share/man/man1/pdfattach.1.bz2
- ^/usr/share/man/man1/pdfdetach.1.bz2
- ^/usr/share/man/man1/pdffonts.1.bz2
- ^/usr/share/man/man1/pdfimages.1.bz2
- ^/usr/share/man/man1/pdfinfo.1.bz2
- ^/usr/share/man/man1/pdfseparate.1.bz2
- ^/usr/share/man/man1/pdfsig.1.bz2
- ^/usr/share/man/man1/pdftocairo.1.bz2
- ^/usr/share/man/man1/pdftohtml.1.bz2
- ^/usr/share/man/man1/pdftoppm.1.bz2
- ^/usr/share/man/man1/pdftops.1.bz2
- ^/usr/share/man/man1/pdftotext.1.bz2
- ^/usr/share/man/man1/pdfunite.1.bz2
# Gpgme split. Only ship Qt module
- ^/usr/bin/gpgme-config
- ^/usr/bin/gpgme-json
- ^/usr/bin/gpgme-tool
- ^/usr/lib/python.*/site-packages/gpg
- ^/usr/lib64/cmake/Gpgmepp/GpgmeppConfig.cmake
- ^/usr/lib64/cmake/Gpgmepp/GpgmeppConfigVersion.cmake
- ^/usr/lib64/libgpgme.so
- ^/usr/lib64/libgpgme.so.*
- ^/usr/lib64/libgpgmepp.so
- ^/usr/lib64/libgpgmepp.so.*
- ^/usr/lib64/pkgconfig/gpgme-glib.pc
- ^/usr/lib64/pkgconfig/gpgme.pc
- ^/usr/lib64/pkgconfig/gpgmepp.pc
- ^/usr/share/aclocal/gpgme.m4
- ^/usr/share/doc/gpgme-.*/.*
- ^/usr/share/info/gpgme.info.*
- ^/usr/share/man/man1/gpgme-json.1.bz2
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.* /etc/portage/
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build" . }}
# cleanup ccache
- CCACHE_DIR=/var/cache/ccache/ ccache -C
- emerge -C dev-qt/linguist-tools && emerge --depclean
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
