steps:
- bash build.sh
package_dir: /luetbuild/modules
requires:
- name: "mocaccino-full"
  category: "kernel"
  version: ">=0"
env:
- SUFFIX={{ .Values.suffix }}
- KERNEL_TYPE={{ .Values.prefix }}
- ARCH={{.Values.arch}}
# $ARCH can't be amd64 here, X86_64 is used here
if [ $ARCH == "amd64" ];
  ARCH = "x86_64"
fi
excludes:

- /boot/vmlinuz-.*
- /build.sh$
- /build.yaml$
- /definition.yaml$
