steps:
- bash build.sh
package_dir: /luetbuild/modules
requires:
- name: "mocaccino-full"
  category: "kernel"
  version: ">=0"
env:
- SUFFIX={{ .Values.suffix }}
- KERNEL_TYPE={{ .Values.prefix }}
# $ARCH can't be amd64 here, X86_64 is used here
{{$arch := ""}}
{{if eq .Values.arch "amd64" }}
{{$arch = "X86_64"}}
{{end}}
- ARCH={{$arch}}
excludes:

- /boot/vmlinuz-.*
- /build.sh$
- /build.yaml$
- /definition.yaml$
