includes:
- /usr$
- /usr/share/wallpapers$
- ^/usr/share/wallpapers/Autumn$
- ^/usr/share/wallpapers/Autumn/.*
- ^/usr/share/wallpapers/Canopee$
- ^/usr/share/wallpapers/Canopee/.*
- ^/usr/share/wallpapers/ColdRipple$
- ^/usr/share/wallpapers/ColdRipple/.*
- ^/usr/share/wallpapers/FlyingKonqui$
- ^/usr/share/wallpapers/FlyingKonqui/.*
- ^/usr/share/wallpapers/Grey$
- ^/usr/share/wallpapers/Grey/.*
- ^/usr/share/wallpapers/Kite$
- ^/usr/share/wallpapers/Kite/.*
- ^/usr/share/wallpapers/Mountain$
- ^/usr/share/wallpapers/Mountain/.*
- ^/usr/share/wallpapers/OneStandsOut$
- ^/usr/share/wallpapers/OneStandsOut/.*
- ^/usr/share/wallpapers/Path$
- ^/usr/share/wallpapers/Path/.*
- ^/usr/share/wallpapers/SafeLanding$
- ^/usr/share/wallpapers/SafeLanding/.*
- ^/usr/share/wallpapers/ScarletTree$
- ^/usr/share/wallpapers/ScarletTree/.*
unpack: true
requires:
- name: plasma
  version: ">=0"
  category: layers
