excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable elementary
- emaint sync -r elementary
# {{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- eselect repository remove elementary
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
