excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable binaryden
- emaint sync -r binaryden
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- sed -i '/\[Greeter\]/ a\background=\/usr\/share\/wallpapers\/mocaccino-wallpaper\/background.jpg' /etc/lightdm/slick-greeter.conf
- eselect repository remove binaryden
- emerge -C app-eselect/eselect-repository
requires:
- category: "apps"
  name: "lightdm"
  version: ">=0"
