excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- USE="introspection vala -qt5" emerge -1 x11-misc/lightdm
- cp -rf package.accept_keywords /etc/portage/
- USE="-subversion -mercurial" emerge app-portage/layman
- layman -L
- echo "y" | layman -a binaryden
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
# - sed -i '/[Greeter]/a background=\/usr\/share\/wallpapers\/mocaccino-wallpaper\/background.jpg' /etc/lightdm/slick-greeter.conf
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
