excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository enable guru
- emaint sync -r guru
# bump to latest version
- cp /var/db/repos/guru/x11-themes/qogir-icon-theme/qogir-icon-theme-2020.11.22.ebuild /var/db/repos/guru/x11-themes/qogir-icon-theme/qogir-icon-theme-2025.02.15.ebuild
- sed -i 's/2020\.11\.22/2025-02-15/g' /var/db/repos/guru/x11-themes/qogir-icon-theme/qogir-icon-theme-2025.02.15.ebuild
- ebuild /var/db/repos/guru/x11-themes/qogir-icon-theme/qogir-icon-theme-2025.02.15.ebuild manifest
steps:
{{ template "portage_build" . }}
# silly issue, fix it here for now
- mv /usr/share/icons/Qogir-dark /usr/share/icons/Qogir-Dark
requires:
- category: "layers"
  name: "X"
  version: ">=0"
