excludes:
{{ template "portage_excludes" }}
prelude:
- git clone https://gitlab.gnome.org/p3732/os-installer.git
- cd os-installer && meson build/ && ninja -C build/
steps:
- cd os-installer && ninja -C build/ install
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
