excludes:
{{ template "portage_excludes" }}
- ^/usr/local/share/icons/hicolor/icon-theme.cache
- ^/usr/local/share/applications/mimeinfo.cache
- ^/usr/local/share/glib-2.0/schemas/gschemas.compiled
prelude:
- git clone https://gitlab.gnome.org/p3732/os-installer.git
- cd os-installer && meson build/ && ninja -C build/
steps:
- cd os-installer && ninja -C build/ install
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
