env:
# RUSTFLAGS="-A warnings -C link-arg=-fuse-ld=mold"
prelude:
- |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    git clone --recurse-submodules https://github.com/pop-os/cosmic-epoch && \
    cd cosmic-epoch && \
    build
steps:
- cd cosmic-epoch && install
requires:
- category: "layers"
  name: "X"
  version: ">=0"
excludes:
{{ template "portage_excludes" }}
