env:
prelude:
- |
    PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
    git clone --recurse-submodules https://github.com/pop-os/cosmic-epoch && \
    cd cosmic-epoch && \
    build && \
    make
steps:
- cd cosmic-epoch && make PREFIX="/usr" install
requires:
- category: "layers"
  name: "X"
  version: ">=0"
excludes:
{{ template "portage_excludes" }}
