excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.unmask /etc/portage/
- cp firefox_optimized /etc/portage/env
- USE="abi_x86_64 amd64 cpu_flags_x86_sse2 elibc_glibc icu kernel_linux npm snapshot ssl system-icu system-ssl" emerge -1 net-libs/nodejs
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build" . }}
# Moccacino OS customization for bookmarks, start site and bookmarks toolbar.
- cp -rf distribution/distribution.ini /usr/lib64/firefox/distribution/
requires:
- category: "layers"
  name: "X"
  version: ">=0"
