excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
{{ template "portage_prelude_build_gentoo_binary" . }}
steps:
{{ template "portage_build" . }}
# Moccacino OS customization for bookmarks, start site and bookmarks toolbar.
- cp -rf distribution/distribution.ini /usr/lib64/firefox/distribution/
requires:
- category: "layers"
  name: "X"
  version: ">=0"
