excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ ( index .Values.labels "emerge.jobs" ) | default "3" }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
# Moccacino OS customization for bookmarks, start site and bookmarks toolbar.
# - cp -rf distribution/distribution.ini /usr/lib64/firefox/distribution/
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
