excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.env /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp firefox_optimized /etc/portage/env
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
# Moccacino OS customization for bookmarks, start site and bookmarks toolbar.
- cp -rf distribution/distribution.ini /usr/lib64/firefox/distribution/
requires:
- category: "layers"
  name: "X"
  version: ">=0"
