excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
{{ template "portage_prelude_build" . }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- sed -i '/syslog/d' /lib/systemd/system/lightdm.service
- sed -i 's/#background=/background=\/usr\/share\/wallpapers\/mocaccino-wallpaper\/background.jpg/g' /etc/lightdm/lightdm-gtk-greeter.conf
- sed -i 's/#user-background=/user-background=false/g' /etc/lightdm/lightdm-gtk-greeter.conf
- sed -i 's/#xft-hintstyle=/xft-hintstyle=hintfull/g' /etc/lightdm/lightdm-gtk-greeter.conf
- sed -i 's/#xft-rgba=/xft-rgba=rgb/g' /etc/lightdm/lightdm-gtk-greeter.conf
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
