excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.accept_keywords /etc/portage/
- USE="-subversion -mercurial" emerge app-portage/layman
- layman -L
- echo "y" | layman -a gentoo-zh
{{ template "portage_prelude_build" . }}
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
requires:
- category: "layers"
  name: "X"
  version: ">=0"
