excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- USE="introspection curl" emerge -1 sys-apps/flatpak sys-apps/fwupd
{{ template "portage_prelude_build" . }}
steps:
{{ template "portage_build" . }}
- etc-update -q --automode -5
requires:
- category: "layers"
  name: "kde-common"
  version: ">=0"
