excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
- USE="introspection curl" emerge -1 sys-apps/flatpak sys-apps/fwupd
steps:
{{ template "portage_build" . }}
- emerge -C dev-util/itstool
- etc-update -q --automode -5
requires:
- category: "layers"
  name: "kde-common"
  version: ">=0"
