excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_prelude_build" . }}
{{ template "portage_copy_package_files" . }}
steps:
{{ template "portage_build" . }}
requires:
- category: "buildbase"
  name: "qemu"
  version: ">=0"
- category: "buildbase"
  name: "gnome-common"
  version: ">=0"
requires_final_images: true
