excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
steps:
{{ template "portage_build" . }}
- emerge -C dev-util/itstool
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
