excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
{{ template "portage_copy_package_files" . }}
steps:
{{ template "portage_build" . }}
- emerge -C dev-util/itstool
requires:
- category: "layers"
  name: "gnome-common"
  version: ">=0"
