excludes:
{{ template "portage_excludes" }}

env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- USE="-subversion -mercurial" emerge layman
- echo "y" | layman -o https://mirror.git.trinitydesktop.org/gitea/TDE/tde-packaging-gentoo/raw/branch/master/Documentation/overlay.xml -f -a trinity-official
steps:
- emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
- etc-update -q --automode -5
requires:
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
