excludes:
{{ template "portage_excludes" }}
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.env /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository add trinity-official git https://mirror.git.trinitydesktop.org/gitea/TDE/tde-packaging-gentoo.git
- emaint sync -r trinity-official
# tdm fails to build, remove from meta
- sed -rie 's/tdm.+$//g' /var/db/repos/trinity-official/trinity-base/tdebase-meta/tdebase-meta-14.1.2.ebuild
- ebuild /var/db/repos/trinity-official/trinity-base/tdebase-meta/tdebase-meta-14.1.2.ebuild manifest
{{ template "portage_prelude_build" . }}
steps:
- emerge -1 www-misc/hldig::trinity-official
{{ template "portage_build" . }}
- eselect repository remove -f trinity-official
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
