excludes:
{{ template "portage_excludes" }}
env:
{{ template "portage_env" . }}
prelude:
- cp -rf package.use /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- cp -rf package.env /etc/portage/
- emerge -1 app-eselect/eselect-repository
- eselect repository add trinity git https://github.com/Fat-Zer/trinity.git
- emaint sync -r trinity
steps:
{{ template "portage_build" . }}
- eselect repository remove -f trinity
- emerge -C app-eselect/eselect-repository
requires:
- category: "layers"
  name: "X"
  version: ">=0"
