excludes:
- ^/var/cache/distfiles
- ^/usr/portage/distfiles
- ^/var/db/repos
- ^/var/cache/edb
- ^/usr/portage
- ^/var/db/pkg
- ^/var/lib/portage
- ^/var/log
- ^/var/lib/module-rebuild
- ^/luetbuild
- ^/lib/modules/.*-mocaccino/modules\..*

env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
- JOBS={{ .Values.emerge.jobs }}
  #prelude:
# Add custom package.use for each package in the collection
#- cp -rf {{.Values.name}}/package.use /etc/portage/
prelude:
- cp -rf package.license /etc/portage/
- emerge -t -o -j ${JOBS} {{ join " " .Values.emerge.packages }}

steps:
- emerge -t -j ${JOBS} {{ join " " .Values.emerge.packages }}

requires:
{{- if .Values.lts }}
- category: "buildbase"
  name: "mocaccino-lts-sources"
  version: ">=0"
{{- else}}
- category: "buildbase"
  name: "mocaccino-sources"
  version: ">=0"
{{- end}}
- category: "buildbase"
  name: "X"
  version: ">=0"
requires_final_images: true
