excludes:
{{ template "portage_excludes" }}
- ^/var/lib/module-rebuild
- ^/usr/lib/modules/.*-mocaccino/modules\..*
- ^/etc/portage/repos.conf/eselect-repo.conf
env:
{{ template "portage_env" . }}
prelude:
{{ if contains "xone" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable guru
- emaint sync -r guru
{{- end}}
# TODO Be smarter then this.
{{ if eq "v4l2loopback-lts" .Values.name }}
- ln -s /usr/src/linux /lib/modules/6.12.51-mocaccino/build
- emerge -1 dev-util/pahole
{{- end}}
{{ if eq "v4l2loopback" .Values.name }}
- echo "media-video/v4l2loopback ~amd64" > /etc/portage/package.accept_keywords/v4l2loopback.accept_keywords
- ln -s /usr/src/linux /lib/modules/6.17.1-mocaccino/build
- emerge -1 dev-util/pahole
{{- end}}
{{ if contains "rtl8812au" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable rasdark
- emaint sync -r rasdark
{{- end}}
{{ if contains "rtl8192eu" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable guru
- emaint sync -r guru
{{- end}}
{{ if contains "rtl88x2bu" .Values.name }}
- emerge -1 app-eselect/eselect-repository
- eselect repository enable sam_c
- emaint sync -r sam_c
{{- end}}
- cp -rf package.license /etc/portage/
- cp -rf package.accept_keywords /etc/portage/
- emerge -t -o -j ${JOBS} {{ join " " .Values.emerge.packages }}
steps:
- emerge -t -j ${JOBS} {{ join " " .Values.emerge.packages }}
{{- if .Values.xone }}
- emerge -C app-eselect/eselect-repository
{{- end}}
{{- if contains "nvidia" .Values.name }}
- |
   mkdir -p /etc/dracut.conf.d/ && \
   cp nvidia-dracut.conf /etc/dracut.conf.d/99-nvidia.conf
{{- end}}
requires:
- category: "kernel-sources"
{{- if .Values.lts }}
  name: "mocaccino-lts-sources"
{{- else}}
  name: "mocaccino-sources"
{{- end}}
  version: ">=0"
